---

- include: 'debian.yml'
  when: ansible_facts.os_family == 'Debian'

- include: 'redhat.yml'
  when: ansible_facts.os_family == 'RedHat'

- include: 'route_table_configuration.yml'
  tags: configuration

- include: 'bond_configuration.yml'
  when: interfaces_bond_interfaces is defined
  tags: configuration

- include: 'bridge_configuration.yml'
  when: interfaces_bridge_interfaces is defined
  tags: configuration

- include: 'ethernet_configuration.yml'
  when: interfaces_ether_interfaces is defined
  tags: configuration

- name: Ensure interfaces are configured
  meta: flush_handlers

- name: RedHat | ensure network service is started and enabled
  # NOTE: This handles the case where there are no configuration
  # changes.
  become: true
  service:
    name: network
    enabled: true
    state: started
  when: ansible_facts.os_family == 'RedHat'
